version: "3.9"
services:
  selenium:
    build: .
    volumes:
      - .:/app/code
      - test_reports:/reports
    command: pytest --verbose test_game.py -x --pdb --junitxml=/reports/test_report.xml

volumes:
  test_reports:
    
