pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                /* Wishlist:
                - switch vue and tailwind from dev to prod files
                - perform SCSS/LESS compiling
                */
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                dir("./testing") {
                  sh 'ls -la'
                  sh 'USERID=$(id -u) GROUPID=$(id -g) docker-compose up'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
      always {
        junit '**/*.xml'
        emailext (
          to: '$DEFAULT_RECIPIENTS',
          subject: '$DEFAULT_SUBJECT',
          body: '$DEFAULT_CONTENT'
        )
      }
    }
}