pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                /* Wishlist:
                - switch vue and tailwind from dev to prod files
                - perform SCSS/LESS compiling
                */
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                dir("./testing") {
                  // sh 'docker-compose up'
                  sh 'ls -la'
                  sh '/usr/local/bin/docker-compose up'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
      always {
        junit './testing/*.xml'
      }
    }
}